import React, { useState } from "react";
import Head from "next/head";
import Navbar from '@/components/Navbar';
import Image from "next/image";
import { Roboto_Condensed } from "next/font/google";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Link from "@mui/material/Link";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Container from "@mui/material/Container";
import styles from "@/styles/App.module.scss";

const robotoFont = Roboto_Condensed({ subsets: ["latin"] });

export default function Home() {
  const [countString, setCount] = useState("");
  const [count, setCount2] = useState("");

  const clickBtn = () => {
    setCount("Yes! Yes! Yes!");
    console.log("Button clicked", countString);
  };

  const clickBtn2 = () => {
    const newCount = `Go ! Go ! Go !`;
    setCount2(newCount);
    console.log("Button clicked", newCount);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <Container sx={{fontFamily: robotoFont}}>
          <Box sx={{ p: 5, textAlign: "center" }}>
            <Typography
              variant="h4"
              gutterBottom
              component="h1"
              sx={{
                fontSize: "3.2em",
                fontWeight: "600",
                cursor: "pointer",
                textDecoration: "underline", ":hover": { bgcolor: "skyblue", color: "indigo", borderRadius: "0.25rem" },
              }}
            >
              React + MUI
            </Typography>
            <Grid container justifyContent="center" spacing={2}>
              <Grid item>
                <Link
                  href="https://nextjs.org/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    className={styles.logo}
                    src="/next.svg"
                    alt="Next.js Logo"
                    width={180}
                    height={50}
                    priority
                  />
                </Link>
              </Grid>
            </Grid>
            <Box sx={{ my: 2 }}>
              <Button variant="outlined" onClick={clickBtn} sx={{ fontSize: '1.5rem', border: "1px solid transparent", m: 1, ":hover": { bgcolor: "#feb28e", color: "indigo", borderRadius: "0.25rem" } }}>
                Start? {countString}
              </Button>
              <Button variant="outlined" onClick={clickBtn2} sx={{ fontSize: '1.5rem', border: "1px solid transparent", m: 1, ":hover": { bgcolor: "skyblue", color: "indigo", borderRadius: "0.25rem" } }}>
                Keep going? {count}
              </Button>
            </Box>
            <Typography variant="body1" sx={{ my: 2, textAlign: "center" }}>
              Click on the NEXT.JS logos to learn more
            </Typography>
            <Typography
              variant="h4"
              gutterBottom
              component="h1"
              sx={{
                fontSize: "3.2em",
                fontWeight: "600",
                cursor: "pointer",
                textDecoration: "underline",
                ":hover": { bgcolor: "skyblue", color: "indigo", borderRadius: "0.25rem" },
              }}
            >
              Hello world!
            </Typography>
          </Box>
        </Container>
      </Box>
    </>
  );
}
